#!/bin/bash

user=$1 # management user
pass=$2 # management user password
port=$3 # management port
addr=$4 # base metric address
type=$5 # data type
attr=$6 # attribute name
metr=$7 # metric name

case $addr in
    mbean) addr='{"core-service":"platform-mbean"},{"type":"TYPE"}'    ;;
    deplm) addr='{"deployment":"application.war"},{"subsystem":"TYPE"}';;
    mpool) addr='{"core-service":"platform-mbean"},{"type":"memory-pool"},{"name":"TYPE"}'        ;;
    garbg) addr='{"core-service":"platform-mbean"},{"type":"garbage-collector"},{"name":"TYPE"}'  ;;
    datas) addr='{"subsystem":"datasources"},{"data-source":"DataaccessDS"},{"statistics":"TYPE"}';;
esac

data='{"operation":"read-attribute","name":"ATTR","address":[ADDR]}'
data="${data//ADDR/$addr}"
data="${data//TYPE/$type}"
data="${data//ATTR/$attr}"

wget -qO- http://$user:$pass@localhost:$port/management \
--header="Content-Type: application/json" --post-data="$data" | \

python -c "
import sys, json
metr = '$metr'
if metr:
    print json.load(sys.stdin)['result'][metr]
else:
    print json.load(sys.stdin)['result']"
