#!/bin/bash

user=${1}       # management user
pass=${2}       # management user password
port=${3}       # management port
http=${4:-wget} # http agent wget\curl
addr=${5}       # base metric address
type=${6}       # data type
attr=${7}       # attribute name
metr=${8}       # metric name

case $addr in
    mbean) addr='{"core-service":"platform-mbean"},{"type":"TYPE"}'    ;;
    deplm) addr='{"deployment":"application.war"},{"subsystem":"TYPE"}';;
    mpool) addr='{"core-service":"platform-mbean"},{"type":"memory-pool"},{"name":"TYPE"}'        ;;
    garbg) addr='{"core-service":"platform-mbean"},{"type":"garbage-collector"},{"name":"TYPE"}'  ;;
    datas) addr='{"subsystem":"datasources"},{"data-source":"DataaccessDS"},{"statistics":"TYPE"}';;
esac

data='{"operation":"read-attribute","name":"ATTR","address":[ADDR]}'
data="${data//ADDR/$addr}"
data="${data//TYPE/$type}"
data="${data//ATTR/$attr}"

parser () {
python -c "
import sys, json
metr = '$metr'
if metr:
    print json.load(sys.stdin)['result'][metr]
else:
    print json.load(sys.stdin)['result']"
}

case $http in
    curl) curl -qo- --anyauth --user $user:$pass --header "Content-Type: application/json" \
          --data "$data" http://localhost:$port/management 2>/dev/null  | parser;;
    wget) wget -qO- http://$user:$pass@localhost:$port/management \
          --header="Content-Type: application/json" --post-data="$data" | parser;;
esac
